version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/test_task
    ports:
      - 3000:3000
    image: app:bookapp
    container_name: bookapp_container
    command: npm start
